spring:
  application:
    name: todo-api

  datasource:
    url : jdbc:postgresql://localhost:5432/TodoDb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto : update
    show-sql : true

  jwt:
    secret:H6t98yyB26F5jQTUDtVSYXEVhXDQdEI0VV0zbL1rrbt


server:
  port: 5000